name: Comment on pylint issue comparison

on: [pull_request]

jobs:
  make_issues_comment:
    runs-on: ubuntu-latest
    steps:
    # install python
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    # checkout the PR
    - uses: actions/checkout@v2
    # cache the pip step for speed
    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}
    # install the dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[testing]
    # make the report
    - uses: SJShaw/pylint-compare@main
      with:
        targets: antismash *.py
        install_pylint: false
